name: CI
 
on:
  push:
    branches: [ main ]

  workflow_dispatch:
env:
    CONTAINER_IMAGE: docker.pkg.github.com/${{github.repository}}/test:${{github.sha}}
    CONTAINER_IMAGE_LATEST: docker.pkg.github.com/${{github.repository}}/test:latest
jobs:
  docker-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and tag
      run: docker build -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
    - name: Run box version	    
      uses: docker://CONTAINER_IMAGE_LATEST
      with:
        #entrypoint: /opt/box/box
        args: version
